### ISSUE TITLE
Unraid docker s6-rc-compile fatal

### ISSUE THREAD

**Issue by tjorim** [Roxedus/docker-conreq#14]
**Describe the bug**
Try to install the conreq docker but not able to access it

**To Reproduce**
1. Go to Unraid Apps
2. Search for Conreq
3. Install and run it
4. Open the log
5. See error

**Expected behavior**
Being able to open Conreq on the designated port

**Logs**
s6-rc-compile: fatal: during resolution of bundle user: undefined service name config

**Comment by mariushosting** [comment]
s6-rc-compile: fatal: during resolution of bundle user: undefined service name config

Same error here. The conreq docker container is no longer working since the last update. @Roxedus

**Comment by Archmonger** [comment]
Users can temporarily use the `hotio` docker while waiting for a solution here

**Comment by tjorim** [comment]
> Users can temporarily use the `hotio` docker while waiting for a solution here

Hotio took his repo (and docker images) offline and recommends this as a replacement.

**Comment by Archmonger** [comment]
@Roxedus latest docker builds successfully but does not launch the rc.d conreq service.

**Comment by mariushosting** [comment]
[custom-init] No custom services found, skipping...
s6-rc-compile: fatal: unable to read /etc/s6-overlay/s6-rc.d/init-config-end/type: No such file or directory
