### ISSUE TITLE
dockerfile doesnt expose any ports

### ISSUE THREAD

**Issue by kungfoome** [Roxedus/docker-conreq#6]
Dockerfile doesn't expose any ports. Looks like it should expose 8000

**Comment by Roxedus** [comment]
It's not a bug, it doesn't break core docker functionality. You can vaguely argue it's against best practice.

**Comment by kungfoome** [comment]
@Roxedus thats fine, but the only option is to report a bug

**Comment by Archmonger** [comment]
Resolved in latest develop commits
